### ISSUE TITLE
`ArgumentException` looking for JDKs

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/android-tools#154]
This happened in a test here: 

* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5751716&view=ms.vss-test-web.build-test-results-tab&runId=33356848&resultId=100155&paneView=attachments
* Seems unrelated to the changes: https://github.com/xamarin/xamarin-android/pull/6745

```
23:21:22.063   1:7>/Users/runner/android-toolchain/dotnet/packs/Microsoft.Android.Sdk.Darwin/31.0.200-ci.pr.gh6745.77/tools/Xamarin.Android.Tooling.targets(69,5): warning : An exception occurred while validating the Java SDK installation in '/Users/runner/Library/Android/jdk-11' that was found while searching the paths from '$JI_JAVA_HOME'. Ensure that the Android section of the Visual Studio options has a valid Java SDK directory configured. To use a custom SDK path for a command line build, set the 'JavaSdkDirectory' MSBuild property to the custom path. Exception: Not a directory (Parameter 'homePath') [/Users/runner/work/1/a/TestRelease/02-14_22.59.11/temp/NothingToBindclass-parse/UnnamedProject.csproj]
                     System.ArgumentException: Not a directory (Parameter 'homePath')
                        at Xamarin.Android.Tools.JdkInfo..ctor(String homePath, String locator, Action`2 logger) in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs:line 57
                        at Xamarin.Android.Tools.JdkInfo..ctor(String homePath, String locator) in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs:line 97
                        at Xamarin.Android.Tools.JdkInfo.TryGetJdkInfo(String path, Action`2 logger, String locator) in /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs:line 347 (TaskId:57)
```

The MSBuild log says `$JI_JAVA_HOME` is:
```
JI_JAVA_HOME = /Users/runner/Library/Android/jdk-11
```

**Comment by jonpryor** [comment]
Odds are that `$JI_JAVA_HOME`, while set, does not exist:

https://github.com/xamarin/xamarin-android-tools/blob/a7f4d30677d0ffd39996ad76784357e87ad8678d/src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs#L56-L57
https://github.com/xamarin/xamarin-android-tools/blob/a7f4d30677d0ffd39996ad76784357e87ad8678d/src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs#L343-L354
https://github.com/xamarin/xamarin-android-tools/blob/a7f4d30677d0ffd39996ad76784357e87ad8678d/src/Xamarin.Android.Tools.AndroidSdk/Properties/Resources.resx#L120-L126


Feels like the test environment is probably broken.

**Comment by jonathanpeppers** [comment]
This issue is stale, I think we should just close.
